### ISSUE TITLE
Uncaught ReferenceError: toasterHub is not defined

### ISSUE THREAD

**Issue by dev** [masmerise/livewire-toaster#12]
Everything works great, but for some reason I'm getting this error on page load:
![Screenshot 2023-07-07 at 10 29 26](https://github.com/masmerise/livewire-toaster/assets/12158001/bfc6d14b-658e-4786-acbd-9c9253a52388)

app.blade.php:
![Screenshot 2023-07-07 at 10 30 28](https://github.com/masmerise/livewire-toaster/assets/12158001/d9d057b5-aedb-4e91-8a65-e04dd07c51ee)

Tailwind.config.js:
![Screenshot 2023-07-07 at 10 30 48](https://github.com/masmerise/livewire-toaster/assets/12158001/a5c66184-4109-4087-b872-89a9e7186dc2)

app.js:
![Screenshot 2023-07-07 at 10 35 36](https://github.com/masmerise/livewire-toaster/assets/12158001/256a33d1-107c-4fc2-b95b-44a5742e8d27)

Laravel version: v10.10.1
Toaster version: 1.2.1
Livewire version: v2.12.3

**Comment by mabdullahsari** [comment]
You seem to be using Alpine from a CDN. That's not supported.

Please use Alpine through an NPM Module instead.

**Comment by Altffenser** [comment]
I am going through the same situation, the difference of this case to mine is that I have Alpine installed from NPM and I still get these errors... anyone who has had this happen and can help me a bit with this?

Laravel version: 10.8
PHP version: 8.2
Livewire version 2.12.6
Toaster version: 1.3

**Comment by chatisk** [comment]
Same here, any clue @mabdullahsari  ?

**Comment by mabdullahsari** [comment]
> Same here, any clue @mabdullahsari ?
> 
> Whats the AlpineJs requirement?

Livewire 3 no longer requires you to pull in Alpine yourself. This error should no longer be possible with Toaster 2.

**Comment by chatisk** [comment]
> > Same here, any clue @mabdullahsari ?
> > 
> > Whats the AlpineJs requirement?
> 
> Livewire 3 no longer requires you to pull in Alpine yourself. This error should no longer be possible with Toaster 2.

Thank you for your immediate response. I was talking about the required version of alpine.  I am using alpine V2 and this package , 1.3. I guess that's why I have issues.please include that in your md cause I switched to yours since it nowhere said that it needs alpine V3. Anyways, thanks again

**Comment by mabdullahsari** [comment]
> > > Same here, any clue @mabdullahsari ?
> > > Whats the AlpineJs requirement?
> > 
> > 
> > Livewire 3 no longer requires you to pull in Alpine yourself. This error should no longer be possible with Toaster 2.
> 
> Thank you for your immediate response. I was talking about the required version of alpine. I am using alpine V2 and this package , 1.3. I guess that's why I have issues.please include that in your md cause I switched to yours since it nowhere said that it needs alpine V3. Anyways, thanks again

You should follow the Livewire 3 upgrade guide first. This package is not meant to be used as a standalone thing. It assumes you also use Livewire for other things.
