### ISSUE TITLE
RTL Language Alignment Issue with Toast Messages

### ISSUE THREAD

**Issue by codenashwan** [masmerise/livewire-toaster#13]
When my website is in Arabic or any RTL (Right-to-Left) language, the toast messages are displayed correctly, but the text alignment remains on the left side instead of aligning to the right as expected. This misalignment disrupts the user experience and readability for RTL language users.

I believe this issue could be resolved by implementing proper RTL support for toast messages in the package. It would greatly enhance the usability of the "livewire-toaster" package for websites with RTL language content.

I kindly request that you consider addressing this concern and implementing a fix to ensure that toast messages align correctly for RTL languages. If there are any workarounds or suggestions you may have in the meantime, I would greatly appreciate your guidance.

Thank you for your attention to this matter, and I look forward to your response. 

<img width="2056" alt="Screenshot 2023-07-18 at 2 45 02 AM" src="https://github.com/masmerise/livewire-toaster/assets/35005761/66122789-81b0-425e-b394-86c70a6ae305">
o your response.

**Comment by mabdullahsari** [comment]
I'll try to take a look at this sometime this week. If you need this asap, you can publish the blade view and swap the `text-left` and `text-right` classes in order to "support" RTL text temporarily. For this, please refer to [View customization](https://github.com/masmerise/livewire-toaster#view-customization).

سلام

**Comment by mabdullahsari** [comment]
@codenashwan It can stay open. I'll add native RTL support within the library itself. 👍

**Comment by codenashwan** [comment]
> @codenashwan It can stay open. I'll add native RTL support within the library itself. 👍

**Use this package is great :** 
[https://github.com/usernotnull/tall-toasts](https://github.com/usernotnull/tall-toasts)

**Comment by mabdullahsari** [comment]
Lol, ok then. I'm not adding any RTL support.

**Comment by mabdullahsari** [comment]
RTL has been added with release 1.3.0
