### ISSUE TITLE
Composer and php version conflit

### ISSUE THREAD

**Issue by jameskanyiri** [masmerise/livewire-toaster#17]
Problem 1
    - masmerise/livewire-toaster[0.1, ..., 0.4] require laravel/framework ^9.0 -> found laravel/framework[v9.0.0, ..., v9.52.15] but it conflicts with your root composer.json require (^10.10).
    - masmerise/livewire-toaster[1.0.0, ..., 1.3.0] require php ~8.2 -> your php version (8.1.17) does not satisfy that requirement.

**Comment by mabdullahsari** [comment]
#8
