### ISSUE TITLE
Uncaught ReferenceError toasts & toasterhub

### ISSUE THREAD

**Issue by Altffenser** [masmerise/livewire-toaster#18]
I get this error. I read in another post that it was due to the inclusion of Alpine via CDN. My case is different because Alpine in my project is referenced through NPM. I have tried many things like changing the import order in the "app.js" file as well as in my layout and none of that works. What could be causing these errors?

Anyone who has had this happen and can help me a bit with this?

![tSJecCF](https://github.com/masmerise/livewire-toaster/assets/32808128/eb8436de-2cf4-4d19-a786-d56d8beae8ae)

![y8w8iHw](https://github.com/masmerise/livewire-toaster/assets/32808128/3738cd27-4881-4ead-9538-294f0132253f)

Laravel version: 10.8
PHP version: 8.2
Livewire version 2.12.6
Toaster version: 1.3

**Comment by mabdullahsari** [comment]
You'll have to show how your `app.js` file is composed.

**Comment by Altffenser** [comment]
> You'll have to show how your `app.js` file is composed.

An apology, I have managed to solve it and is that at the time of importing the module in the "app.js" file must be referenced with a name.

`import Toaster from '../../vendor/masmerise/livewire-toaster/resources/js';`

Then
`Alpine.plugin(Toaster);`

thanks to @dev

**Comment by mabdullahsari** [comment]
> > You'll have to show how your `app.js` file is composed.
> 
> An apology, I have managed to solve it and is that at the time of importing the module in the "app.js" file must be referenced with a name.
> 
> `import Toaster from '../../vendor/masmerise/livewire-toaster/resources/js';`
> 
> Then `Alpine.plugin(Toaster);`
> 
> thanks to @dev

The current README docs is for v2 which doesn't require that. 😉
Glad you got it sorted out!
