### ISSUE TITLE
Toasts is not showing after livewire redirect from component

### ISSUE THREAD

**Issue by bee-interactive** [masmerise/livewire-toaster#19]
Hi!

I have some issue to show the toasts after a redirect from a Livewire component. I'm assuming it's because of the redirect but as explain is the readme, it should work.

Here's my actual configuration:

Laravel version: 10.20
PHP version: 8.2
Livewire version 3.0
Toaster version: 2.0

Here's the save method inside my Livewire component:

```
public function save()
{
    $category = Category::create($this->validate());

    return redirect()->to(route('home'))->success(__('Your category has been created'));
}
```

The rest of the component is only a mount method and some validation rules.

I have tried different approaches inside the save method too:

```
return redirect(route('home')->success(__('Your category has been created'));
```

```
Toaster::success(__('Your category has been created'));

return redirect(route('home');
```

I have added the Toast package successfully since I can make it work in other components without the redirect (send toast after a modal close event for exemple)

Any ideas were I miss something?

Thanks in advance!

**Comment by mabdullahsari** [comment]
Can you please read [this issue](https://github.com/masmerise/livewire-toaster/issues/4) thoroughly, go through each step and report back with your findings? Thanks.

**Comment by bee-interactive** [comment]
Hi! Thanks for the feedback.

I have tried with the redirect response, still the same result. I don't have any errors, it just redirects me to the page but no toasts is showned. 

Another thing I forgot to mention is that the Component is a ModalComponent, used from the wire-elements/modal package. Maybe a conflict with this one?

**Comment by mabdullahsari** [comment]
@bee-interactive I don't think so.

- Are your own endpoints, as well as Livewire's message endpoint making use of the `web` middleware group? You can verify this using `php artisan route:list`.
- If the above question's answer is yes, are you using the `StartSession` middleware in the `web` group?
- Are you sure the front-end receives the `toaster:received` events? You can inspect this in the `Network` tab of Google Chrome, or Safari ... The `dispatches` key should contain at least 1 `toaster:received` event.

**Comment by bee-interactive** [comment]
Yes everything is correctly set up. I use the toasts in other parts of the application and it's working fine. Except the parts were I redirect the user after an action.. Strange

**Comment by mabdullahsari** [comment]
Could you verify that the `ModalComponent` is not the culprit here? Are you redirecting in a non-modal component, ie. standard component elsewhere?

**Comment by bee-interactive** [comment]
I'm simply redirecting to the home page. No components on the homepage..

**Comment by mabdullahsari** [comment]
Sure, but where you are redirecting **from** is equally important. That's my question 👍

**Comment by bee-interactive** [comment]
Sorry :-)

I have the same behavior within a standard controller. After the save, the user is redirected but no toasts is shown.

Here's the update method inside a basic Laravel controller:

```
public function update(EventUpdateRequest $request, Event $event): RedirectResponse
{
    $event->update($request->validated());

    return Redirect::route('home')->info(__('The informations have been updated'));
}
```

**Comment by mabdullahsari** [comment]
Hi @bee-interactive

Is there any link I could use? Thanks a lot.

**Comment by bee-interactive** [comment]
@mabdullahsari Hi! I will prepare a test repository!

**Comment by mabdullahsari** [comment]
Hi @bee-interactive 

Any news on your test repository?

**Comment by bee-interactive** [comment]
@mabdullahsari Hi! Sorry for the late response. It turns out upgrading my Laravel application and upgrading to the latest version of Livewire fixed the issue.
