### ISSUE TITLE
Support for Laravel 10

### ISSUE THREAD

**Issue by emanuelnogueiras** [masmerise/livewire-toaster#22]
**This is what I get when I try to add this to a Laravel 10 project.**
--
Problem 1
    - Root composer.json requires masmerise/livewire-toaster ^0.4.0 -> satisfiable by masmerise/livewire-toaster[0.4].
    - masmerise/livewire-toaster 0.4 requires laravel/framework ^9.0 -> found laravel/framework[v9.0.0, ..., v9.52.15] but the package is fixed to v10.22.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by mabdullahsari** [comment]
Please bump the package version to 2.0.0 at least.
