### ISSUE TITLE
Compatibility with laravel/framework ^10.10

### ISSUE THREAD

**Issue by kdjafarizad** [masmerise/livewire-toaster#24]
Hello, 
I guess that livewire-toaster is, at the time, strictly compatible with livewire 2 but maybe unstable with livewire 3, but it would be nice to support livewire 2 installations on laravel 10 by bumping requirements. It should stay stable in laravel 10.

Any plans to do it soon?

Thanks

**Comment by mabdullahsari** [comment]
Toaster 1 is compatible with L10 & LW2
Toaster 2 compatible with L10 & LW3

Both are stable versions.
