### ISSUE TITLE
Uncaught ReferenceError: toasterHub is not defined

### ISSUE THREAD

**Issue by angelbendgr8-dev** [masmerise/livewire-toaster#29]
![Screenshot 2023-11-19 at 22 29 17](https://github.com/masmerise/livewire-toaster/assets/63807149/89ede934-28bb-440e-9258-686f547e91c5)

**Comment by mabdullahsari** [comment]
You should follow the guide properly. If you're on v1, check out [the v1 docs](https://github.com/masmerise/livewire-toaster/tree/1.3.0) instead.
