### ISSUE TITLE
Only support 8.3?

### ISSUE THREAD

**Issue by aoeng** [masmerise/livewire-toaster#32]
Young man, you have taken a narrow road.
Others try their best to be backward compatible, but you, my friend, are doing the exact opposite.

**Comment by mabdullahsari** [comment]
Hey, old man, Toaster is feature-complete & supports 8.2 up to version 2.0.3 so feel free to use that.

**Comment by mabdullahsari** [comment]
I will add a compatibility matrix to make this clear. Thanks for bringing it up. 👍
