### ISSUE TITLE
Uncaught ReferenceError: toasterHub is not defined

### ISSUE THREAD

**Issue by restucciaquito** [masmerise/livewire-toaster#33]
![Captura de pantalla 2023-12-18 a la(s) 18 51 33](https://github.com/masmerise/livewire-toaster/assets/26152924/8dd55fdc-0cf9-466b-b3e4-20da6dc8065e)

**Comment by amansaini419** [comment]
What need to do for this?

**Comment by emtiazzahid** [comment]
@restucciaquito at least say what was the issue, so others can understand
