### ISSUE TITLE
ReferenceError: toasterHub is not defined

### ISSUE THREAD

**Issue by amansaini419** [masmerise/livewire-toaster#39]
![image](https://github.com/masmerise/livewire-toaster/assets/6827644/facddeb6-7b30-4fb6-8f0d-aff597f3e1ba)

I already install the package through composer. I also performed the following steps:

![image](https://github.com/masmerise/livewire-toaster/assets/6827644/e8f7ffca-6911-4693-80bf-e1c2667b6a00)

![image](https://github.com/masmerise/livewire-toaster/assets/6827644/58e4d79b-aea0-4495-903d-8ca9efd477fa)

But still things not working for me. Can I have little assistance?

**Comment by mabdullahsari** [comment]
Hi, how are you building your scripts?

**Comment by mabdullahsari** [comment]
I'm afraid I can't do anything unless I'm provided a clue or repro. 😕

**Comment by amansaini419** [comment]
I resolved the problem. I hope this helps to my friends who are stuck in this problem.

![image](https://github.com/masmerise/livewire-toaster/assets/6827644/81ddb546-e03c-43ce-b2ad-2548c9ad56c9)

We need to include app.js in our layout. I am using vite, so I am including like this:
![image](https://github.com/masmerise/livewire-toaster/assets/6827644/4ab6dbfe-37b0-465a-932f-cf15bbcf526b)

**Comment by richarddewit** [comment]
Also don't forget to run `npm run build` 😅

**Comment by jsanchezlunia** [comment]
> Also don't forget to run `npm run build` 😅

Thanks for the reminder, it was my case!
