### ISSUE TITLE
Bootstrap template support

### ISSUE THREAD

**Issue by emtiazzahid** [masmerise/livewire-toaster#42]
After the setup it seems the style not supporting as I'm using bootstrap
![image](https://github.com/masmerise/livewire-toaster/assets/10188029/08614d94-dd44-4e5a-8ad7-b34ffde58133)

**Comment by mabdullahsari** [comment]
Yes, it's not. You have to eject the views and style the component yourself.

See: https://github.com/masmerise/livewire-toaster?tab=readme-ov-file#view-customization
