### ISSUE TITLE
Toasts not showing when using navigate: true

### ISSUE THREAD

**Issue by boptom** [masmerise/livewire-toaster#44]
**The problem:**
When using Livewire redirect with `navigate: true` along with `@persist`, the toasts do not show.

```
Toaster::success('Toast Message');

$this->redirect('/', navigate: true);
```

In layout:

```
@persist('toaster')
<x-toaster-hub />
@endpersist
```

Docs on navigation here: https://livewire.laravel.com/docs/navigate#redirects
Possibly related to: https://github.com/masmerise/livewire-toaster/issues/28

**What happens:**
The page navigates, but the toast does not show.

**What is expected?**
The page navigates and the toast shows "Toast Message".

**Why not use regular redirects?**
Previous toasts are not persisted and disappear on navigation with regular redirects from the backend.

**Why use @persist?**
To persist the toast messages through navigation.

Laravel: 11.5.0
Livewire: 3.4.11

**Comment by mabdullahsari** [comment]
Hey, thanks for the in-depth explanation! I'll try taking a look at it today.

**Comment by mabdullahsari** [comment]
Hey! Unfortunately, I'm bereft of time lately and haven't had the opportunity to investigate what the root cause of this problem might be. I am most definitely welcoming pull requests that address this issue. 

Thank you!

**Comment by boptom** [comment]
I'll give it another go when I have some time too. I'm not familiar with Laravel/Livewire internals and got lost following methods around last I tried.

I also couldn't figure out how to write a failing test for this. Any ideas?

**Comment by mabdullahsari** [comment]
Feel free to re-open this issue if you submit a PR in the near future!

**Comment by mabdullahsari** [comment]
This issue has been resolved with the latest release!

**Comment by bligede767** [comment]
> This issue has been resolved with the latest release!

Hello, I use toaster version 2.6 in my Laravel 11. In this code, the toaster doesn't appear.

`    public function store()
    {
        $data = $this->validated();

        try {
            Event::deactivateEvents($data['is_active']);

            $data->save();

            $this->reset();

            Toaster::success('New event created.');

            return $this->redirect(route('admin.events.index'), true);
        } catch (Exception $e) {
            Toaster::error($e->getMessage());
        }
    }`

And if I use the @persist, the appearing animation not works, yet the out animation works
`
@persist('toaster')
<x-toaster-hub />
@endpersist
`

**Comment by mabdullahsari** [comment]
> > This issue has been resolved with the latest release!
> 
> Hello, I use toaster version 2.6 in my Laravel 11. In this code, the toaster doesn't appear.
> 
> ```
>     public function store()
>     {
>         $data = $this->validated();
> 
>         try {
>             Event::deactivateEvents($data['is_active']);
> 
>             $data->save();
> 
>             $this->reset();
> 
>             Toaster::success('New event created.');
> 
>             return $this->redirect(route('admin.events.index'), true);
>         } catch (Exception $e) {
>             Toaster::error($e->getMessage());
>         }
>     }
> ```
> 
> And if I use the [@persist](https://github.com/persist), the appearing animation not works, yet the out animation works `@persist('toaster') <x-toaster-hub /> @endpersist`

Try [this](https://github.com/masmerise/livewire-toaster/pull/55#issuecomment-2612520248)

**Comment by bligede767** [comment]
> > > This issue has been resolved with the latest release!
> > 
> > 
> > Hello, I use toaster version 2.6 in my Laravel 11. In this code, the toaster doesn't appear.
> > ```
> >     public function store()
> >     {
> >         $data = $this->validated();
> > 
> >         try {
> >             Event::deactivateEvents($data['is_active']);
> > 
> >             $data->save();
> > 
> >             $this->reset();
> > 
> >             Toaster::success('New event created.');
> > 
> >             return $this->redirect(route('admin.events.index'), true);
> >         } catch (Exception $e) {
> >             Toaster::error($e->getMessage());
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And if I use the [@persist](https://github.com/persist), the appearing animation not works, yet the out animation works `@persist('toaster') <x-toaster-hub /> @endpersist`
> 
> Try [this](https://github.com/masmerise/livewire-toaster/pull/55#issuecomment-2612520248)

I already use this below. The toaster can appear, but the appearing animation not working. In other words, the toaster appears without animation (blink)
```
@persist('toaster')
 <x-toaster-hub />
@endpersist
```
