### ISSUE TITLE
Uncaught ReferenceError: toasterHub is not defined

### ISSUE THREAD

**Issue by aqshah20** [masmerise/livewire-toaster#45]
alpinejs:5 
 Uncaught ReferenceError: toasterHub is not defined
    at [Alpine] toasterHub([], JSON.parse('{\u0…), <anonymous>:3:16)

keep getting above error even I have added this  line <x-toaster-hub /> before end body tag.
can anyone help me why?

**Comment by mabdullahsari** [comment]
Please follow the installation guide properly.

People who have had a similar issue always ended up having a misconfigured environment: https://github.com/masmerise/livewire-toaster/issues/39

Thanks!
