### ISSUE TITLE
Include icon next to the message

### ISSUE THREAD

**Issue by claytongf** [masmerise/livewire-toaster#47]
How can I include icons inside Toaster?
I didn't see in the documentation but in the video demonstration, the icon appears.

**Comment by mabdullahsari** [comment]
Those are simple emojis, like this one! 🚀

**Comment by claytongf** [comment]
Can you consider to add icons as a new feature?

**Comment by mabdullahsari** [comment]
You can easily add them yourself by ejecting the default package views, and customizing them to your liking! 😄

**Comment by claytongf** [comment]
I mean, add this feature to get icons dinamically. =)
Ex:
```
Toaster::success($message, $icon);
```

The $icon can be entire attribute, like, 

```
<i class="fa-solid fa-check"></i> //in this case, I'm using Font Awesome as example
```
