### ISSUE TITLE
Combination Laravel- & PHP versions

### ISSUE THREAD

**Issue by edwinvdpol** [masmerise/livewire-toaster#48]
This plugin works fine on both Laravel 11 and 10, with both PHP 8.2 and 8.3.

Why drop PHP- & Laravel versions so strict, like, I am running Laravel 11 on PHP 8.2.
This combination is not possible, as version 2.0.3 (which still has PHP 8.2 support), only supports Laravel 10.

So I have to downgrade my Laravel version to 10, or upgrade my PHP version to 8.3.

Is it possible to support both (and any other workable) combinations?

Cheers!

**Comment by mabdullahsari** [comment]
Hey! 👋

> Why drop PHP- & Laravel versions so strict

That's because I am always using the latest major versions on my own projects, and I have very limited time to provide support for my open source packages, so I need to make a conscious choice here. What's your reason for not upgrading to 8.2? Curious to know!

**Comment by edwinvdpol** [comment]
I am running on PHP 8.2 now, but I'm not on PHP 8.3 yet. 😉
I understand your personal preferences, after all, it is your project, don't get me wrong.
I do think that not everybody has the possibility to upgrade their PHP versions as "fast" as you.
For instance when you are on a shared hosting environment.
The backwards compatibility of Laravel is great, you only need to add another PHP version to your test workflow to be sure it works with older PHP versions.

Then again, I see you added typed class constants which are only available in PHP 8.3.

What I am trying too say is, that more people could benefit from this package if the version requirements were a little less strict, that's all. 😉 

Great package though, that's why I made the effort to comment on this.

Have a good day, and keep up the good work!

**Comment by mabdullahsari** [comment]
Fair enough! I’ll add 8.2 support tomorrow. I don’t think it’s going to be a huge hinderance in this case. 👍

**Comment by mabdullahsari** [comment]
8.2 support has been added! Please upgrade and use version **2.3.0**. 

Een fijne dag nog. 😉

**Comment by edwinvdpol** [comment]
Thank you! 🎉
