### ISSUE TITLE
Toasts stack up when I'm on another tab

### ISSUE THREAD

**Issue by VenoM9078** [masmerise/livewire-toaster#50]
![image (24)](https://github.com/user-attachments/assets/5112be09-26ca-4f65-bcba-bf5cf22e6e2b)

As the title states, I've a method that is called every 30 seconds, let's call it auto-save. And when I'm off page, it obviously still works. But the toasts, instead of disappearing after 30 seconds like they would if I'm on-page, they don't disappear and just stack up. 

Kindly suggest a fix.

To reproduce?

Add a toaster to a function that is called every 10-30 seconds or so, and minimize the browser/tab.

**Comment by mabdullahsari** [comment]
Unfortunately, this is default browser behavior. Tabs that go out of focus are placed in a low priority queue and most of the time JavaScript timer execution halts during that period. There is nothing that can be done about this, so you have to alter the logic on your side. Stop autosaving when the user blurs the tab as you know they won't be making changes anyway. 

Good luck.

**Comment by mabdullahsari** [comment]
`2.4.0` fixes this issue, please upgrade!
