### ISSUE TITLE
Add custom variables such as URL, description, etc

### ISSUE THREAD

**Issue by alexanderjp** [masmerise/livewire-toaster#51]
Is there a way to pass URL and other variables?

**Comment by mabdullahsari** [comment]
Can you provide a use case? What's the reason you want to do this?

**Comment by mabdullahsari** [comment]
You can already do this for your translation strings, for what it's worth.

**Comment by alexanderjp** [comment]
For our messages we use the title, description and url variables. 

A workaround was to package the variables inside a json string then reference them inside the notification blade. 



-------



On Sep 9, 2024, at 2:22 AM, Muhammed Sari ***@***.***> wrote:

﻿


Can you provide a use case? What's the reason you want to do this?

**Comment by mabdullahsari** [comment]
Can you provide a code example? It is still not entirely clear to me.

**Comment by alexanderjp** [comment]
Here is our hub.blade.php


<div role="status" id="toaster" ***@***.***($toasts), @js($config))" @class([
 'fixed z-50 p-4 w-full flex flex-col pointer-events-none sm:p-6',
 'bottom-0' => $alignment->is('bottom'),
 'top-1/2 -translate-y-1/2' => $alignment->is('middle'),
 'top-0' => $alignment->is('top'),
 'items-start rtl:items-end' => $position->is('left'),
 'items-center' => $position->is('center'),
 'items-end rtl:items-start' => $position->is('right'),
 ])>
 <template x-for="toast in toasts" :key="toast.id">
 <div x-show="toast.isVisible"
 x-init="$nextTick(() => toast.show($el))"
 @if($alignment->is('bottom'))
 x-transition:enter-start="translate-y-12 opacity-0"
 x-transition:enter-end="translate-y-0 opacity-100"
 @elseif($alignment->is('top'))
 x-transition:enter-start="-translate-y-12 opacity-0"
 x-transition:enter-end="translate-y-0 opacity-100"
 @else
 x-transition:enter-start="opacity-0 scale-90"
 x-transition:enter-end="opacity-100 scale-100"
 @endif
 x-transition:leave-end="opacity-0 scale-90"
 @class(['relative duration-500 transform transition ease-in-out max-w-xs w-full pointer-events-auto', 'text-center' => $position->is('center')])
 :class="toast.select({ error: 'text-white', info: 'text-black', success: 'text-white', warning: 'text-white' })"
 >
 <div class="inline-block select-none not-italic px-6 py-3 rounded shadow-lg text-sm w-full {{ $alignment->is('bottom') ? 'mt-3' : 'mb-3' }}"

 :class="toast.select({ error: 'bg-red-500', info: 'bg-gray-200', success: 'bg-green-600', warning: 'bg-orange-500' })">
 <strong x-text="JSON.parse(toast.message).title"></strong><br>
 <span x-text="JSON.parse(toast.message).description"></span>
 <a :href="JSON.parse(toast.message).url" class="text-blue-500 underline" x-show="JSON.parse(toast.message).url"> Click here </a>
 {{-- <a :href="JSON.parse(toast.message).url" class="text-blue-500 underline" target="_blank" x-show="JSON.parse(toast.message).url">Click here</a> --}}
 </div>

 @if($closeable)
 <button @click="toast.dispose()" ***@***.***('close')" class="absolute right-0 p-2 focus:outline-none rtl:right-auto rtl:left-0 {{ $alignment->is('bottom') ? 'top-3' : 'top-0' }}">
 <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
 <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
 </svg>
 </button>
 @endif
 </div>
 </template>
</div>




Alexander 

On Sep 10, 2024, at 7:49 AM, Muhammed Sari ***@***.***> wrote:


Can you provide a code example? It is still not entirely clear to me.

**Comment by alexanderjp** [comment]
Sorry, having a difficult time posting code in the comments.  Here is a PDF of the code.

[hub.blade.php.pdf](https://github.com/user-attachments/files/16970466/hub.blade.php.pdf)

**Comment by mabdullahsari** [comment]
That didn't do it either 😅. 

Anyway, I think I know what you're getting at now: you want to be able to trigger some user actions from within the toast. 

Unfortunately, this is out of scope for this package. The sheer small size of this package allows it to be lightning fast and that was the main goal from the get-go. You can use something like [`filament/notifications`](https://filamentphp.com/docs/3.x/notifications/installation) (it can be used standalone) for the functionality that you desire.

**Comment by alexanderjp** [comment]
I will look into. 
Thank you

-------
Alexander



On Sep 12, 2024, at 4:50 AM, Muhammed Sari ***@***.***> wrote:

﻿


Closed #51 as not planned.
