### ISSUE TITLE
 The message value cannot be empty.

### ISSUE THREAD

**Issue by prykris** [masmerise/livewire-toaster#56]
Why not, why not just ignore it? I have to wrap my toaster calls in if statements.

**Comment by mabdullahsari** [comment]
Unfortunately, that would result in empty toasts being shown to the users which is probably undesired in the vast majority of cases. I'm afraid you'll need to keep your if statements to ensure a good experience for your users!

Have fun coding.

**Comment by prykris** [comment]
Just to clarify, I wasn’t suggesting the library should actually show an empty toast. What I meant was it’d be helpful if the library could quietly skip the toast call if the message is empty. Throwing an exception feels a bit harsh for that case, especially since it’s easy to hit an empty message in common scenarios like these:

Dynamic data: When a toast message is populated from an API response or user input, an empty value can slip through, triggering an exception instead of a silent skip.

Localization: Sometimes translations or content keys are missing, which can result in an empty message unintentionally.

Optional messages: In cases where toast messages are optional, an empty message shouldn’t necessarily break the flow with an exception.

I can add a check on my end, no problem, but this tweak might help make it a bit more user-friendly for similar cases.

Thanks for considering it!
