### ISSUE TITLE
Prevent > 1 toast at any one time?

### ISSUE THREAD

**Issue by jscott-yps** [masmerise/livewire-toaster#59]
Are there are methods to detect how many toasts are currently displayed? Or better yet a way to track/key toasts to prevent the same one being fired again.

**Comment by mabdullahsari** [comment]
Why would you want to do that? Dispatching multiple toasts is in the core design of the library, and thus a “duplicate” is only a notion on your end. If you could elaborate the problem further, I might be of a help.

**Comment by ditsbroefs** [comment]
Say a user updates a model and as a result you want to store the modification and show a toast confirming the update ('Model has been updated'). If the user makes 10 changes in 30 seconds you might want to 'throttle' the toasts. Or at least not show a new instance of the same message, while it is still being showed.

**Comment by mabdullahsari** [comment]
> Say a user updates a model and as a result you want to store the modification and show a toast confirming the update ('Model has been updated'). If the user makes 10 changes in 30 seconds you might want to 'throttle' the toasts. Or at least not show a new instance of the same message, while it is still being displayed.

Makes sense. You can always [extend the behavior](https://github.com/masmerise/livewire-toaster?tab=readme-ov-file#extending-behavior) of this package in an effortless way. It would mean that you create a `ThrottlingCollector` in your own system and register it with the IoC container so the toasts you dispatch get sent through this throttle mechanism before it reaches the end user.

A PR is always welcome.

**Comment by jscott-yps** [comment]
Took the words right out of my mouth, thanks @ditsbroefs - Another example, if we want to show a validation message or a an error from a form, if the user repeatedly clicks the button they will end up with a stack of dozens and dozens of simultaneous identical toasts. Made even more painful if the timeout is on the longer side because they'll need to manually close them all to get rid of the visual clutter. Will look into the extending behaviour in the meantime. The hack i was running with currently was to export the hub and then:

![image](https://github.com/user-attachments/assets/9f092dfe-077e-42c5-995d-e828dd5d3efb)

But this is pretty unpleasant. 

Thanks.

**Comment by mabdullahsari** [comment]
> Although again, i'm unsure how this could be used without having access to the current list of toasts to compare against.

You'll need to keep a history of the toasts that were dispatched for a specific user. However, this seems like a tedious job while a live queue is available on the client-side. But this also means that a similar pipeline needs to be set up on the client-side in a similar vein. 

I'll see what I can do.

**Comment by mabdullahsari** [comment]
Please upgrade to `2.4.0`!

**Comment by ditsbroefs** [comment]
You are amazing!

**Comment by mabdullahsari** [comment]
I added a new replacement option as suggested by @jscott-yps. Upgrade to `2.5.0` if you'd like to use that instead.
