### ISSUE TITLE
php 8.1 & laravel 10 error

### ISSUE THREAD

**Issue by aldozumaran** [masmerise/livewire-toaster#8]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires masmerise/livewire-toaster ^0.4.0 -> satisfiable by masmerise/livewire-toaster[0.4].
    - masmerise/livewire-toaster 0.4 requires laravel/framework ^9.0 -> found laravel/framework[v9.0.0, ..., v9.52.9] but it conflicts with your root composer.json require (^10.0).

**Comment by mabdullahsari** [comment]
`Toaster` requires PHP 8.2. Please upgrade your PHP version.

**Comment by aldozumaran** [comment]
Hi @mabdullahsari i can't upgrade php, can you fix that? "php": "^8.1|^8.2" or 8.*

**Comment by mabdullahsari** [comment]
> Hi @mabdullahsari i can't upgrade php, can you fix that? "php": "^8.1|^8.2" or 8.*

Sorry, no. This package uses features only available as of PHP 8.2. You can consider using a fork in the meantime, until you are able to upgrade your PHP version.
